# Block加Markov混合模型

本测试严格遵循根目录 `00_PLAN.md`，主要结果使用训练参数固定后的response-before held-out likelihood。

In [1]:
from pathlib import Path
import sys,json,pandas as pd
WORKSPACE=Path.cwd();RUNTIME=WORKSPACE/'tmp'/'jupyter-notebook'/'runtime';CORE=WORKSPACE/'Markov_test'/'model_artifacts'
for p in (RUNTIME,CORE):
    if str(p) not in sys.path:sys.path.insert(0,str(p))

In [2]:
from markov_test_core import run_test04
result=run_test04()
result

hybrid 1 1 209

hybrid 1 2 211

hybrid 1 3 171

hybrid 1 4 211

hybrid 2 1 76

hybrid 2 2 235

hybrid 2 3 84

hybrid 2 4 133

hybrid 3 1 268

hybrid 3 2 300

hybrid 3 3 263

hybrid 3 4 300

hybrid 4 1 163

hybrid 4 2 217

hybrid 4 3 159

hybrid 4 4 300

hybrid 5 1 300

hybrid 5 2 300

hybrid 5 3 300

hybrid 5 4 300

hybrid 6 1 300

hybrid 6 2 300

hybrid 6 3 300

hybrid 6 4 300

hybrid 7 1 300

hybrid 7 2 300

hybrid 7 3 204

hybrid 7 4 300

hybrid 8 1 300

hybrid 8 2 300

hybrid 8 3 300

hybrid 8 4 300

hybrid 9 1 300

hybrid 9 2 300

hybrid 9 3 237

hybrid 9 4 280

hybrid 10 1 300

hybrid 10 2 300

hybrid 10 3 300

hybrid 10 4 300

hybrid 11 1 300

hybrid 11 2 300

hybrid 11 3 273

hybrid 11 4 196

hybrid 12 1 300

hybrid 12 2 187

hybrid 12 3 300

hybrid 12 4 97

                        model  ll_per_trial
0  exchangeable_block_mixture     -0.794568
1                original_hmm     -0.810573
2           block_plus_markov     -0.787089

In [3]:
validation=json.loads((WORKSPACE/'Markov_test'/'04_block_plus_markov'/'validation.json').read_text())
display(pd.Series(validation,name='passed').to_frame())
assert all(validation.values())

                    passed
48_fits               True
83210_predictions     True
unique_predictions    True
finite                True

## 解释边界

本步骤结论见同目录 `conclusion.md`；最终解释由全部八项测试共同决定。