# Trial-order shuffle control: four-fold held-out comparison

**Objective.** Fit original and shuffled versions in the same four saved run-level folds and compare held-out one-step-ahead predictive density.

## Evaluation contract

- Original subject-session-run blocks retain identical fold membership across versions.
- Every fold fits only the other three folds.
- Test parameters are fixed; test data never update π, transitions, or kappas.
- Each test segment restarts from the training-derived π.
- `p_*` are smoothed state inference; `test_log_predictive_density` is the primary out-of-sample prediction.

In [1]:
from pathlib import Path
import sys,json,pandas as pd
WORKSPACE=Path.cwd(); RUNTIME=WORKSPACE/'tmp'/'jupyter-notebook'/'runtime'; CORE=WORKSPACE/'shuffle_control'/'model_artifacts'
for p in (RUNTIME,CORE):
    if str(p) not in sys.path: sys.path.insert(0,str(p))
from shuffle_control_core import protected_snapshot, run_heldout, finalize_protection
before=protected_snapshot()

## Execute all 96 training fits and held-out scoring

In [2]:
result=run_heldout(force=True)
display(result['comparison'])

cv original subject 01 fold 1: 140 iter

cv original subject 01 fold 2: 248 iter

cv original subject 01 fold 3: 131 iter

cv original subject 01 fold 4: 206 iter

cv original subject 02 fold 1: 129 iter

cv original subject 02 fold 2: 200 iter

cv original subject 02 fold 3: 266 iter

cv original subject 02 fold 4: 125 iter

cv original subject 03 fold 1: 166 iter

cv original subject 03 fold 2: 65 iter

cv original subject 03 fold 3: 107 iter

cv original subject 03 fold 4: 86 iter

cv original subject 04 fold 1: 90 iter

cv original subject 04 fold 2: 76 iter

cv original subject 04 fold 3: 117 iter

cv original subject 04 fold 4: 73 iter

cv original subject 05 fold 1: 300 iter

cv original subject 05 fold 2: 300 iter

cv original subject 05 fold 3: 159 iter

cv original subject 05 fold 4: 300 iter

cv original subject 06 fold 1: 107 iter

cv original subject 06 fold 2: 168 iter

cv original subject 06 fold 3: 108 iter

cv original subject 06 fold 4: 72 iter

cv original subject 07 fold 1: 300 iter

cv original subject 07 fold 2: 71 iter

cv original subject 07 fold 3: 121 iter

cv original subject 07 fold 4: 59 iter

cv original subject 08 fold 1: 240 iter

cv original subject 08 fold 2: 300 iter

cv original subject 08 fold 3: 291 iter

cv original subject 08 fold 4: 269 iter

cv original subject 09 fold 1: 173 iter

cv original subject 09 fold 2: 130 iter

cv original subject 09 fold 3: 300 iter

cv original subject 09 fold 4: 193 iter

cv original subject 10 fold 1: 300 iter

cv original subject 10 fold 2: 300 iter

cv original subject 10 fold 3: 300 iter

cv original subject 10 fold 4: 209 iter

cv original subject 11 fold 1: 190 iter

cv original subject 11 fold 2: 75 iter

cv original subject 11 fold 3: 113 iter

cv original subject 11 fold 4: 221 iter

cv original subject 12 fold 1: 104 iter

cv original subject 12 fold 2: 89 iter

cv original subject 12 fold 3: 84 iter

cv original subject 12 fold 4: 121 iter

cv shuffled subject 01 fold 1: 89 iter

cv shuffled subject 01 fold 2: 128 iter

cv shuffled subject 01 fold 3: 91 iter

cv shuffled subject 01 fold 4: 136 iter

cv shuffled subject 02 fold 1: 192 iter

cv shuffled subject 02 fold 2: 95 iter

cv shuffled subject 02 fold 3: 300 iter

cv shuffled subject 02 fold 4: 252 iter

cv shuffled subject 03 fold 1: 126 iter

cv shuffled subject 03 fold 2: 125 iter

cv shuffled subject 03 fold 3: 126 iter

cv shuffled subject 03 fold 4: 123 iter

cv shuffled subject 04 fold 1: 300 iter

cv shuffled subject 04 fold 2: 300 iter

cv shuffled subject 04 fold 3: 136 iter

cv shuffled subject 04 fold 4: 300 iter

cv shuffled subject 05 fold 1: 300 iter

cv shuffled subject 05 fold 2: 207 iter

cv shuffled subject 05 fold 3: 300 iter

cv shuffled subject 05 fold 4: 300 iter

cv shuffled subject 06 fold 1: 103 iter

cv shuffled subject 06 fold 2: 300 iter

cv shuffled subject 06 fold 3: 180 iter

cv shuffled subject 06 fold 4: 300 iter

cv shuffled subject 07 fold 1: 300 iter

cv shuffled subject 07 fold 2: 300 iter

cv shuffled subject 07 fold 3: 150 iter

cv shuffled subject 07 fold 4: 179 iter

cv shuffled subject 08 fold 1: 129 iter

cv shuffled subject 08 fold 2: 300 iter

cv shuffled subject 08 fold 3: 204 iter

cv shuffled subject 08 fold 4: 194 iter

cv shuffled subject 09 fold 1: 300 iter

cv shuffled subject 09 fold 2: 300 iter

cv shuffled subject 09 fold 3: 300 iter

cv shuffled subject 09 fold 4: 300 iter

cv shuffled subject 10 fold 1: 300 iter

cv shuffled subject 10 fold 2: 300 iter

cv shuffled subject 10 fold 3: 300 iter

cv shuffled subject 10 fold 4: 207 iter

cv shuffled subject 11 fold 1: 76 iter

cv shuffled subject 11 fold 2: 133 iter

cv shuffled subject 11 fold 3: 121 iter

cv shuffled subject 11 fold 4: 300 iter

cv shuffled subject 12 fold 1: 81 iter

cv shuffled subject 12 fold 2: 94 iter

cv shuffled subject 12 fold 3: 300 iter

cv shuffled subject 12 fold 4: 93 iter

,subject_id,original_test_ll_per_trial,shuffled_test_ll_per_trial,original_test_perplexity,shuffled_test_perplexity,original_all_folds_completed,shuffled_all_folds_completed,delta_test_ll_per_trial,delta_test_perplexity
0,1,-0.464688,-0.476292,1.591517,1.610093,True,True,0.011604,-0.018576
1,2,-0.582144,-0.594265,1.789872,1.811699,True,True,0.012121,-0.021826
2,3,-0.478312,-0.487240,1.613349,1.627817,True,True,0.008928,-0.014468
3,4,-0.779799,-0.805385,2.181034,2.237558,True,True,0.025586,-0.056524
4,5,-1.286371,-1.287996,3.619627,3.625514,True,True,0.001625,-0.005887
5,6,-0.913759,-0.931003,2.493680,2.537052,True,True,0.017243,-0.043372
6,7,-0.651470,-0.677276,1.918358,1.968509,True,True,0.025807,-0.050151
7,8,-1.235353,-1.260172,3.439593,3.526028,True,True,0.024819,-0.086435
8,9,-0.864900,-0.870741,2.374768,2.388681,True,True,0.005841,-0.013913
9,10,-1.035067,-1.093238,2.815294,2.983922,True,True,0.058172,-0.168628
10,11,-0.840973,-0.880470,2.318621,2.412034,True,True,0.039498,-0.093413
11,12,-0.955649,-0.987704,2.600358,2.685063,True,True,0.032055,-0.084705

## Quality audit

In [3]:
validation=json.loads((WORKSPACE/'shuffle_control'/'logs'/'heldout_validation.json').read_text())
display(pd.Series(validation,name='passed').to_frame())
assert all(validation.values())
finalize_protection(before)

                                     passed
each_original_trial_once               True
each_shuffled_trial_once               True
same_fold_per_trial                    True
48_folds_per_version                   True
all_fold_rows_present                  True
finite_test_ll                         True
posterior_sums_one                     True
first_trial_pi_independent             True
test_parameters_fixed_from_training    True
no_test_em_updates                     True
all_subjects_compared                  True

## Primary interpretation

In [4]:
c=result['comparison']; display(pd.Series({'subjects_original_better':int((c.delta_test_ll_per_trial>0).sum()),'mean_subject_delta':c.delta_test_ll_per_trial.mean(),'weighted_original_ll':(result['folds'].query("data_version=='original'").test_total_log_likelihood.sum()/result['folds'].query("data_version=='original'").n_test_trials.sum()),'weighted_shuffled_ll':(result['folds'].query("data_version=='shuffled'").test_total_log_likelihood.sum()/result['folds'].query("data_version=='shuffled'").n_test_trials.sum())},name='value').to_frame())

                              value
subjects_original_better  12.000000
mean_subject_delta         0.021942
weighted_original_ll      -0.810573
weighted_shuffled_ll      -0.831003

The formal conclusion is recorded in `shuffle_control_report.md` and is based on held-out one-step-ahead likelihood, not on training likelihood or smoothed posteriors.