# IID and non-Markov baseline analysis

**Objective.** Separate prediction due to single-trial emissions, known prior conditions, exchangeable block heterogeneity, and trial-to-trial HMM transitions using identical four-fold held-out trials.

## Pre-registered execution order

1. Subject-level IID mixture.
2. Prior-width-conditioned IID mixture.
3. Three-class exchangeable block mixture with causal block-type updating but no state transitions.
4. Compare all three with existing original/shuffled HMM results.

The three baselines are order-invariant; Original and Shuffled totals must match fold by fold.

In [1]:
from pathlib import Path
import sys,json,pandas as pd
WORKSPACE=Path.cwd();RUNTIME=WORKSPACE/'tmp'/'jupyter-notebook'/'runtime';CORE=WORKSPACE/'IID'/'model_artifacts'
for p in (RUNTIME,CORE):
    if str(p) not in sys.path:sys.path.insert(0,str(p))
from iid_baseline_core import main
print({'workspace':str(WORKSPACE),'runtime':RUNTIME.exists()})

{'workspace': 'D:\\neuromatch_pod_work\\HMM_me', 'runtime': True}

## Execute full fits and all same-fold held-out tests

Every test response is scored with training-only parameters. No baseline uses future responses; the block mixture only updates its block-type posterior after each observed response.

In [2]:
overall,decomposition,metadata=main(force=True)
display(overall.sort_values(['data_version','ll_per_trial'],ascending=[True,False]))
display(decomposition)

full subject_iid subject 01: iter=75

full prior_conditioned_iid subject 01: iter=159

full exchangeable_block_mixture subject 01: iter=92

full subject_iid subject 02: iter=121

full prior_conditioned_iid subject 02: iter=85

full exchangeable_block_mixture subject 02: iter=81
full subject_iid subject 03: iter=43

full prior_conditioned_iid subject 03: iter=90

full exchangeable_block_mixture subject 03: iter=89
full subject_iid subject 04: iter=57

full prior_conditioned_iid subject 04: iter=122

full exchangeable_block_mixture subject 04: iter=109

full subject_iid subject 05: iter=300

full prior_conditioned_iid subject 05: iter=300

full exchangeable_block_mixture subject 05: iter=135

full subject_iid subject 06: iter=54

full prior_conditioned_iid subject 06: iter=93

full exchangeable_block_mixture subject 06: iter=229
full subject_iid subject 07: iter=34

full prior_conditioned_iid subject 07: iter=293

full exchangeable_block_mixture subject 07: iter=71

full subject_iid subject 08: iter=79

full prior_conditioned_iid subject 08: iter=157

full exchangeable_block_mixture subject 08: iter=158

full subject_iid subject 09: iter=75

full prior_conditioned_iid subject 09: iter=105

full exchangeable_block_mixture subject 09: iter=91
full subject_iid subject 10: iter=62

full prior_conditioned_iid subject 10: iter=300

full exchangeable_block_mixture subject 10: iter=154
full subject_iid subject 11: iter=45

full prior_conditioned_iid subject 11: iter=125

full exchangeable_block_mixture subject 11: iter=300

full subject_iid subject 12: iter=79

full prior_conditioned_iid subject 12: iter=158

full exchangeable_block_mixture subject 12: iter=74
cv subject_iid subject 01 fold 1: iter=52

cv prior_conditioned_iid subject 01 fold 1: iter=192

cv exchangeable_block_mixture subject 01 fold 1: iter=67

cv subject_iid subject 01 fold 2: iter=60

cv prior_conditioned_iid subject 01 fold 2: iter=142

cv exchangeable_block_mixture subject 01 fold 2: iter=74
cv subject_iid subject 01 fold 3: iter=35

cv prior_conditioned_iid subject 01 fold 3: iter=148

cv exchangeable_block_mixture subject 01 fold 3: iter=109
cv subject_iid subject 01 fold 4: iter=52

cv prior_conditioned_iid subject 01 fold 4: iter=300

cv exchangeable_block_mixture subject 01 fold 4: iter=84

cv subject_iid subject 02 fold 1: iter=88

cv prior_conditioned_iid subject 02 fold 1: iter=73

cv exchangeable_block_mixture subject 02 fold 1: iter=70

cv subject_iid subject 02 fold 2: iter=127

cv prior_conditioned_iid subject 02 fold 2: iter=111

cv exchangeable_block_mixture subject 02 fold 2: iter=85

cv subject_iid subject 02 fold 3: iter=156

cv prior_conditioned_iid subject 02 fold 3: iter=59

cv exchangeable_block_mixture subject 02 fold 3: iter=93

cv subject_iid subject 02 fold 4: iter=101

cv prior_conditioned_iid subject 02 fold 4: iter=80

cv exchangeable_block_mixture subject 02 fold 4: iter=75
cv subject_iid subject 03 fold 1: iter=42

cv prior_conditioned_iid subject 03 fold 1: iter=88

cv exchangeable_block_mixture subject 03 fold 1: iter=102

cv subject_iid subject 03 fold 2: iter=111

cv prior_conditioned_iid subject 03 fold 2: iter=92

cv exchangeable_block_mixture subject 03 fold 2: iter=90
cv subject_iid subject 03 fold 3: iter=45

cv prior_conditioned_iid subject 03 fold 3: iter=78

cv exchangeable_block_mixture subject 03 fold 3: iter=77
cv subject_iid subject 03 fold 4: iter=46

cv prior_conditioned_iid subject 03 fold 4: iter=102

cv exchangeable_block_mixture subject 03 fold 4: iter=112
cv subject_iid subject 04 fold 1: iter=58

cv prior_conditioned_iid subject 04 fold 1: iter=300

cv exchangeable_block_mixture subject 04 fold 1: iter=159
cv subject_iid subject 04 fold 2: iter=45

cv prior_conditioned_iid subject 04 fold 2: iter=119

cv exchangeable_block_mixture subject 04 fold 2: iter=122
cv subject_iid subject 04 fold 3: iter=40

cv prior_conditioned_iid subject 04 fold 3: iter=104

cv exchangeable_block_mixture subject 04 fold 3: iter=100
cv subject_iid subject 04 fold 4: iter=63

cv prior_conditioned_iid subject 04 fold 4: iter=144

cv exchangeable_block_mixture subject 04 fold 4: iter=93

cv subject_iid subject 05 fold 1: iter=144

cv prior_conditioned_iid subject 05 fold 1: iter=300

cv exchangeable_block_mixture subject 05 fold 1: iter=159

cv subject_iid subject 05 fold 2: iter=300

cv prior_conditioned_iid subject 05 fold 2: iter=300

cv exchangeable_block_mixture subject 05 fold 2: iter=71

cv subject_iid subject 05 fold 3: iter=300

cv prior_conditioned_iid subject 05 fold 3: iter=300

cv exchangeable_block_mixture subject 05 fold 3: iter=116

cv subject_iid subject 05 fold 4: iter=300

cv prior_conditioned_iid subject 05 fold 4: iter=300

cv exchangeable_block_mixture subject 05 fold 4: iter=169
cv subject_iid subject 06 fold 1: iter=50

cv prior_conditioned_iid subject 06 fold 1: iter=98

cv exchangeable_block_mixture subject 06 fold 1: iter=300
cv subject_iid subject 06 fold 2: iter=54

cv prior_conditioned_iid subject 06 fold 2: iter=92

cv exchangeable_block_mixture subject 06 fold 2: iter=206
cv subject_iid subject 06 fold 3: iter=54

cv prior_conditioned_iid subject 06 fold 3: iter=97

cv exchangeable_block_mixture subject 06 fold 3: iter=206

cv subject_iid subject 06 fold 4: iter=51

cv prior_conditioned_iid subject 06 fold 4: iter=130

cv exchangeable_block_mixture subject 06 fold 4: iter=300

cv subject_iid subject 07 fold 1: iter=88

cv prior_conditioned_iid subject 07 fold 1: iter=238

cv exchangeable_block_mixture subject 07 fold 1: iter=214
cv subject_iid subject 07 fold 2: iter=31

cv prior_conditioned_iid subject 07 fold 2: iter=300

cv exchangeable_block_mixture subject 07 fold 2: iter=81
cv subject_iid subject 07 fold 3: iter=36

cv prior_conditioned_iid subject 07 fold 3: iter=191

cv exchangeable_block_mixture subject 07 fold 3: iter=60
cv subject_iid subject 07 fold 4: iter=36

cv prior_conditioned_iid subject 07 fold 4: iter=300

cv exchangeable_block_mixture subject 07 fold 4: iter=95
cv subject_iid subject 08 fold 1: iter=65

cv prior_conditioned_iid subject 08 fold 1: iter=203

cv exchangeable_block_mixture subject 08 fold 1: iter=300

cv subject_iid subject 08 fold 2: iter=185

cv prior_conditioned_iid subject 08 fold 2: iter=137

cv exchangeable_block_mixture subject 08 fold 2: iter=113

cv subject_iid subject 08 fold 3: iter=93

cv prior_conditioned_iid subject 08 fold 3: iter=150

cv exchangeable_block_mixture subject 08 fold 3: iter=134

cv subject_iid subject 08 fold 4: iter=78

cv prior_conditioned_iid subject 08 fold 4: iter=197

cv exchangeable_block_mixture subject 08 fold 4: iter=300

cv subject_iid subject 09 fold 1: iter=74

cv prior_conditioned_iid subject 09 fold 1: iter=94

cv exchangeable_block_mixture subject 09 fold 1: iter=149

cv subject_iid subject 09 fold 2: iter=68

cv prior_conditioned_iid subject 09 fold 2: iter=89

cv exchangeable_block_mixture subject 09 fold 2: iter=93

cv subject_iid subject 09 fold 3: iter=112

cv prior_conditioned_iid subject 09 fold 3: iter=90

cv exchangeable_block_mixture subject 09 fold 3: iter=91

cv subject_iid subject 09 fold 4: iter=71

cv prior_conditioned_iid subject 09 fold 4: iter=195

cv exchangeable_block_mixture subject 09 fold 4: iter=105
cv subject_iid subject 10 fold 1: iter=56

cv prior_conditioned_iid subject 10 fold 1: iter=300

cv exchangeable_block_mixture subject 10 fold 1: iter=146
cv subject_iid subject 10 fold 2: iter=53

cv prior_conditioned_iid subject 10 fold 2: iter=300

cv exchangeable_block_mixture subject 10 fold 2: iter=212
cv subject_iid subject 10 fold 3: iter=43

cv prior_conditioned_iid subject 10 fold 3: iter=125

cv exchangeable_block_mixture subject 10 fold 3: iter=251
cv subject_iid subject 10 fold 4: iter=71

cv prior_conditioned_iid subject 10 fold 4: iter=94

cv exchangeable_block_mixture subject 10 fold 4: iter=166
cv subject_iid subject 11 fold 1: iter=44

cv prior_conditioned_iid subject 11 fold 1: iter=300

cv exchangeable_block_mixture subject 11 fold 1: iter=167
cv subject_iid subject 11 fold 2: iter=44

cv prior_conditioned_iid subject 11 fold 2: iter=86

cv exchangeable_block_mixture subject 11 fold 2: iter=300
cv subject_iid subject 11 fold 3: iter=46

cv prior_conditioned_iid subject 11 fold 3: iter=300

cv exchangeable_block_mixture subject 11 fold 3: iter=300
cv subject_iid subject 11 fold 4: iter=44

cv prior_conditioned_iid subject 11 fold 4: iter=72

cv exchangeable_block_mixture subject 11 fold 4: iter=75
cv subject_iid subject 12 fold 1: iter=54

cv prior_conditioned_iid subject 12 fold 1: iter=300

cv exchangeable_block_mixture subject 12 fold 1: iter=169

cv subject_iid subject 12 fold 2: iter=300

cv prior_conditioned_iid subject 12 fold 2: iter=130

cv exchangeable_block_mixture subject 12 fold 2: iter=78
cv subject_iid subject 12 fold 3: iter=58

cv prior_conditioned_iid subject 12 fold 3: iter=226

cv exchangeable_block_mixture subject 12 fold 3: iter=160
cv subject_iid subject 12 fold 4: iter=63

cv prior_conditioned_iid subject 12 fold 4: iter=128

cv exchangeable_block_mixture subject 12 fold 4: iter=70

,model_name,data_version,n_test_trials,total_ll,subjects,completed_folds,converged_folds,ll_per_trial,perplexity
0,exchangeable_block_mixture,original,83210,-66115.995013,12,48,42,-0.794568,2.213484
6,hmm,original,83210,-67447.761833,12,48,39,-0.810573,2.249196
2,prior_conditioned_iid,original,83210,-68280.044475,12,48,35,-0.820575,2.271806
4,subject_iid,original,83210,-70464.502545,12,48,44,-0.846827,2.332236
1,exchangeable_block_mixture,shuffled,83210,-66115.995013,12,48,42,-0.794568,2.213484
3,prior_conditioned_iid,shuffled,83210,-68280.044475,12,48,35,-0.820575,2.271806
7,hmm,shuffled,83210,-69147.775552,12,48,27,-0.831003,2.295621
5,subject_iid,shuffled,83210,-70464.502545,12,48,44,-0.846827,2.332236

,baseline,baseline_ll_per_trial,hmm_original_gain,hmm_shuffled_gain,order_specific_difference_in_differences
0,subject_iid,-0.846827,0.036255,0.015824,0.02043
1,prior_conditioned_iid,-0.820575,0.010002,-0.010428,0.02043
2,exchangeable_block_mixture,-0.794568,-0.016005,-0.036435,0.02043

## Quality audit

In [3]:
validation=json.loads((WORKSPACE/'IID'/'logs'/'validation.json').read_text())
display(pd.Series(validation,name='passed').to_frame())
assert all(validation.values())

                                passed
valid_rows_each                   True
same_trial_set                    True
same_folds                        True
no_block_fold_leakage             True
288_fold_rows                     True
all_iid_models_order_invariant    True
finite_likelihoods                True
all_folds_completed               True
comparison_has_hmm                True

## Interpretation boundary

The exchangeable block mixture is the strongest non-Markov baseline here: it can causally learn which kind of block it is observing, but its joint block likelihood is invariant to trial order. HMM improvement beyond this model is the relevant residual sequential gain; the original-minus-shuffled HMM contrast remains the direct order control.