# Four-fold held-out comparison for our revised HMM

**Objective.** Refit the three-state subject-specific circular-emission soft-EM HMM in four run-level folds, score every held-out response with a response-before one-step-ahead density, and compare the result with the model benchmarks reported in the source HTML.

## Evaluation contract

- The split unit is the original subject-session-run; missing-response boundaries remain separate HMM segments.
- Folds are deterministic and stratified by subject and prior width.
- Every fold refits subject-specific parameters using training runs only.
- Held-out segment trial 1 uses the training-derived subject-specific $\pi$; later trials use filtering.
- Smoothed posterior probabilities are never used for held-out prediction.
- Existing result folders are read-protected by before/after SHA-256 snapshots.

In [1]:
from pathlib import Path
import json
import sys

WORKSPACE = Path.cwd()
RUNTIME = WORKSPACE / 'tmp' / 'jupyter-notebook' / 'runtime'
CORE_DIR = WORKSPACE / 'HMM_fourfold_comparison' / 'model_artifacts'
for path in (RUNTIME, CORE_DIR):
    if str(path) not in sys.path:
        sys.path.insert(0, str(path))
print({'workspace': str(WORKSPACE), 'runtime_exists': RUNTIME.exists(), 'core_exists': CORE_DIR.exists()})

{'workspace': 'D:\\neuromatch_pod_work\\HMM_me', 'runtime_exists': True, 'core_exists': True}

## Run the complete experiment

This cell performs all 48 subject-by-fold training fits, held-out scoring, bootstrap uncertainty, figures, the combined HTML report, manifests, and validation.

In [2]:
from fourfold_cv_core import main

run_metadata = main()
run_metadata

Using complete cached fold fits and held-out trial scores for validation-only rerun.

{
  "start_time_utc": "2026-07-17T10:52:31.365494+00:00",
  "end_time_utc": "2026-07-17T10:52:59.655266+00:00",
  "runtime_seconds": 28.09830859999056,
  "total_training_fit_runtime_seconds": 276.1021940000646,
  "used_complete_cached_scores": true,
  "python_version": "3.12.13",
  "random_seed": 20260717,
  "n_folds": 4,
  "max_iter": 600,
  "tol": 1e-06,
  "trial_count": 83210,
  "run_count": 388,
  "subject_count": 12,
  "overall_heldout_ll_per_trial": -0.8105676233398648,
  "html_path": "D:\\neuromatch_pod_work\\HMM_me\\HMM_fourfold_comparison\\html\\HMM_fourfold_comparison_with_original_report.html",
  "validation": {
    "valid_trial_count_83210": true,
    "all_heldout_trials_scored_once": true,
    "twelve_subjects": true,
    "four_folds": true,
    "forty_eight_fits": true,
    "no_duplicate_trial_scores": true,
    "three_missing_trials_excluded": true,
    "finite_predictive_likelihood": true,
    "positive_predictive_likelihood": true,
    "finite_log_likelihood": true,
    "prior_predictive_sums_one": true,
    "filtered_sums_one": true,
    "each_trial_is_test_in_its_fold": true,
    "protected_result_folders_unchanged": true,
    "combined_html_exists": true,
    "comparison_figure_exists": true
  }
}

{'start_time_utc': '2026-07-17T10:52:31.365494+00:00',
 'end_time_utc': '2026-07-17T10:52:59.655266+00:00',
 'runtime_seconds': 28.09830859999056,
 'total_training_fit_runtime_seconds': 276.1021940000646,
 'used_complete_cached_scores': True,
 'python_version': '3.12.13',
 'random_seed': 20260717,
 'n_folds': 4,
 'max_iter': 600,
 'tol': 1e-06,
 'trial_count': 83210,
 'run_count': 388,
 'subject_count': 12,
 'overall_heldout_ll_per_trial': -0.8105676233398648,
 'html_path': 'D:\\neuromatch_pod_work\\HMM_me\\HMM_fourfold_comparison\\html\\HMM_fourfold_comparison_with_original_report.html',
 'validation': {'valid_trial_count_83210': True,
  'all_heldout_trials_scored_once': True,
  'twelve_subjects': True,
  'four_folds': True,
  'forty_eight_fits': True,
  'no_duplicate_trial_scores': True,
  'three_missing_trials_excluded': True,
  'finite_predictive_likelihood': True,
  'positive_predictive_likelihood': True,
  'finite_log_likelihood': True,
  'prior_predictive_sums_one': True,
  'filtered_sums_one': True,
  'each_trial_is_test_in_its_fold': True,
  'protected_result_folders_unchanged': True,
  'combined_html_exists': True,
  'comparison_figure_exists': True}}

## Compact result audit

In [3]:
import pandas as pd

output_root = WORKSPACE / 'HMM_fourfold_comparison'
overall = pd.read_csv(output_root / 'csv' / 'our_model_fourfold_overall_summary.csv')
comparison = pd.read_csv(output_root / 'csv' / 'heldout_model_comparison.csv')
validation = (output_root / 'logs' / 'FINAL_VALIDATION_REPORT.txt').read_text(encoding='utf-8')
display(overall)
display(comparison[['model', 'mean_held_out_ll_per_trial', 'ci_low', 'ci_high', 'value_provenance']])
print(validation)

,model,evaluation,n_trials,n_runs,n_subjects,total_log_likelihood,mean_held_out_ll_per_trial,bootstrap_ci_low,bootstrap_ci_high,bootstrap_standard_error,fold_mean,fold_standard_error,converged_fits,total_fits,monotonic_fits
0,Our revised 3-state subject-specific soft-EM HMM,four-fold held-out run-level one-step-ahead,83210,388,12,-67447.331938,-0.810568,-0.860651,-0.76147,0.025291,-0.810841,0.008555,48,48,48

,model,mean_held_out_ll_per_trial,ci_low,ci_high,value_provenance
0,Our revised 3-state subject-specific soft-EM HMM,-0.810568,-0.860651,-0.76147,new fixed four-fold run-level CV; training-onl...
1,Original HTML: Covariate HMM,-0.813300,NaN,NaN,exact value reported in source HTML
2,Original HTML: Static HMM,-0.843100,NaN,NaN,derived from reported independent baseline and...
3,Original HTML: Independent Switching,-0.905200,NaN,NaN,derived from reported covariate delta
4,Original HTML: Serial stimulus + response,-0.910000,NaN,NaN,rounded table value in source HTML
5,Original HTML: Serial response,-0.910000,NaN,NaN,rounded table value in source HTML
6,Original HTML: Serial stimulus,-0.910000,NaN,NaN,rounded table value in source HTML

HMM FOUR-FOLD HELD-OUT VALIDATION
time_utc=2026-07-17T10:52:59.655266+00:00
valid_trial_count_83210: PASS
all_heldout_trials_scored_once: PASS
twelve_subjects: PASS
four_folds: PASS
forty_eight_fits: PASS
no_duplicate_trial_scores: PASS
three_missing_trials_excluded: PASS
finite_predictive_likelihood: PASS
positive_predictive_likelihood: PASS
finite_log_likelihood: PASS
prior_predictive_sums_one: PASS
filtered_sums_one: PASS
each_trial_is_test_in_its_fold: PASS
protected_result_folders_unchanged: PASS
combined_html_exists: PASS
comparison_figure_exists: PASS
overall_status: PASS

## Interpretation boundary

The source HTML does not provide its original fold IDs or per-sequence scores. Therefore its displayed values are external benchmarks, not paired observations on these newly generated folds. A definitive paired bootstrap would require the original fold assignments or refitting all source models on the saved new folds.